#!/usr/bin/env bash
#
# setup-makefiles.sh — generate the vendor makefiles from proprietary-files.txt.
#
# Produces, under ubuntu-touch/vendor/blackview/BL6000Pro/:
#   - BL6000Pro-vendor.mk    PRODUCT_COPY_FILES for every blob (inherited by
#                            device/blackview/BL6000Pro/device.mk)
#   - BoardConfigVendor.mk   vendor board knobs (included by BoardConfig.mk)
#   - Android.mk             build glue (stub; blobs ship via PRODUCT_COPY_FILES)
#
# Run extract-files.sh first so the blobs exist under proprietary/.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# ROOT is the tree that contains device/ and vendor/ — the ubuntu-touch dir in
# this project, or the Halium source root in a real build tree. The device tree
# sits at ROOT/device/blackview/BL6000Pro, so ROOT is three levels up.
ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

BLOB_LIST="${SCRIPT_DIR}/proprietary-files.txt"
VENDOR_DIR="${ROOT}/vendor/blackview/BL6000Pro"
PROP_DIR="${VENDOR_DIR}/proprietary"

mkdir -p "${VENDOR_DIR}"

if [[ ! -d "${PROP_DIR}" ]]; then
    echo "WARNING: ${PROP_DIR} does not exist yet." >&2
    echo "         Run ./extract-files.sh first. Generating makefiles anyway." >&2
fi

YEAR="$(date +%Y)"
LICENSE_HEADER="#
# Copyright (C) ${YEAR} The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the \"License\");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an \"AS IS\" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is generated by setup-makefiles.sh. Do not edit by hand."

# --- BL6000Pro-vendor.mk -----------------------------------------------------
VENDOR_MK="${VENDOR_DIR}/BL6000Pro-vendor.mk"

# Collect "src:dst" pairs into an array first, so continuation backslashes are
# emitted correctly (all lines but the last get a trailing ' \').
pairs=()
while IFS= read -r line; do
    line="${line%%#*}"; line="${line#"${line%%[![:space:]]*}"}"; line="${line%"${line##*[![:space:]]}"}"
    [[ -z "${line}" ]] && continue
    pairs+=("vendor/blackview/BL6000Pro/proprietary/${line#vendor/}:${line}")
done < "${BLOB_LIST}"

{
    echo "${LICENSE_HEADER}"
    echo
    echo "# Auto-generated PRODUCT_COPY_FILES for the BL6000 Pro vendor blobs."
    echo "PRODUCT_COPY_FILES += \\"
    n=${#pairs[@]}
    for i in "${!pairs[@]}"; do
        if (( i < n - 1 )); then
            echo "    ${pairs[i]} \\"
        else
            echo "    ${pairs[i]}"
        fi
    done
} > "${VENDOR_MK}"

# --- BoardConfigVendor.mk ----------------------------------------------------
cat > "${VENDOR_DIR}/BoardConfigVendor.mk" <<EOF
${LICENSE_HEADER}

# Vendor-supplied board configuration for the BL6000 Pro.
# Kept minimal; the blobs are shipped via PRODUCT_COPY_FILES, so no special
# board flags are required beyond what BoardConfig.mk already sets.
EOF

# --- Android.mk --------------------------------------------------------------
cat > "${VENDOR_DIR}/Android.mk" <<EOF
${LICENSE_HEADER}

LOCAL_PATH := \$(call my-dir)

ifeq (\$(TARGET_DEVICE),BL6000Pro)

include \$(call all-makefiles-under,\$(LOCAL_PATH))

endif
EOF

echo "==> Generated:"
echo "    ${VENDOR_MK}"
echo "    ${VENDOR_DIR}/BoardConfigVendor.mk"
echo "    ${VENDOR_DIR}/Android.mk"
echo "==> Blob copy rules: $(grep -c 'proprietary/' "${VENDOR_MK}" || echo 0)"
